version: '3.8'
services:
  fastapi:
    restart: unless-stopped
    image: dtgbot
    volumes:
      - ${REDDIT_ENV}:/app/reddit.env
      - ${GURU_DATA}:/app/guru_data/
    environment:
      - REDDIT_ENV=/app/reddit.env
      - GURU_DATA=/app/guru_data/
      - URL_PREFIX=/dtg
    networks:
      - dtgbot-network
    command: uvicorn DTGBot.fapi.app:app --host 0.0.0.0 --port 8000 --proxy-headers --root-path /dtg

  webserver:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./deploy/server/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
    depends_on:
      - fastapi
    networks:
      - dtgbot-network
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw


networks:
  dtgbot-network:
    driver: bridge

