services:
  fastapi:
    restart: unless-stopped
    build:
      context: .
    image: dtgbot
    volumes:
      - ${REDDIT_ENV}:/app/reddit.env
      - ${GURU_DATA}:/app/guru_data/
    environment:
      - REDDIT_ENV=/app/reddit.env
      - GURU_DATA=/app/guru_data/
    networks:
      - dtgbot-network
#    ports:
#      - "8000:8000"

  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - fastapi
    networks:
      - dtgbot-network

networks:
  dtgbot-network:
    driver: bridge

