version: '3.8'
services:
  fastapi:
    restart: unless-stopped
    build:
      context: .
    image: dtgbot
    volumes:
      - ${REDDIT_ENV}:/app/reddit.env
      - ${GURU_DATA}:/app/guru_data/
    environment:
      - REDDIT_ENV=/app/reddit.env
      - GURU_DATA=/app/guru_data/
      - URL_PREFIX=/dtg
    networks:
      - dtgbot-network
    command: uvicorn DTGBot.fapi.app:app --host 0.0.0.0 --port 8000 --proxy-headers --root-path /dtg


  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/server/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - fastapi
    networks:
      - dtgbot-network

networks:
  dtgbot-network:
    driver: bridge

