version: '3.8'
services:
  fastapi:
    restart: unless-stopped
    image: dtgbot
    volumes:
      - C:\Users\RYZEN\prdev\envs\reddit.env:/app/reddit.env
      - ${GURU_DATA}:/app/guru_data/
      - ${GURU_FRONTEND}:/app/guru_fontend/
    environment:
      - REDDIT_ENV=/app/reddit.env
      - GURU_DATA=/app/guru_data/
      - GURU_FRONTEND=/app/guru_fontend/
    ports:
      - "8000:8000"
    command: uvicorn DTGBot.fapi.app:app --host 0.0.0.0 --port 8000

  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./server/nginx/:/etc/nginx/conf.d:ro
    depends_on:
      - fastapi
    networks:
      - dtgbot-network


networks:
  dtgbot-network:
    driver: bridge


