services:
  fastapi:
    restart: unless-stopped
    build:
      context: ..
    image: dtgbot
    volumes:
      - ${REDDIT_ENV}:/app/reddit.env
      - ${GURU_DATA}:/app/guru_data/
    environment:
      - REDDIT_ENV=/app/reddit.env
      - GURU_DATA=/app/guru_data/
      - URL_PREFIX=/dtg
    command: [ "uvicorn", "DTGBot.fapi.app:app", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers", "--forwarded-allow-ips", "172.19.0.0/16", "--root-path", "/dtg" ]
    networks:
      - dtgbot-network

  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi
    volumes:
      - ./server/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    networks:
      - dtgbot-network

networks:
  dtgbot-network:
    driver: bridge