name: Deploy FastAPI to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H pawrequest.com >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean
        run: |
          ssh paw@pawrequest.com << EOF
            cd ~/dtgbot
            git pull origin main
            git fetch --all
            git reset --hard origin/main
          
            docker compose down
            cd deploy
#            run-prod.sh
            docker compose -f ../docker-compose.yml -f ./docker-compose.dev.yml up --build --force-recreate
               
#            docker compose -f up -d --build --force-recreate
          EOF

#      - name: Check if Nginx container is running
#        run: |

#          container_state=$(docker inspect --format '{{.State.Status}}' dtgbot-nginx-1)
#          if [[ "$container_state" != "running" ]]; then
#            echo "Nginx container is not in 'running' state, it's in $container_state, exiting."
#            exit 1
#          fi
          
